#!/bin/sh
#
# Copyright 2013  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =*= License: GPL-3+ =*=

set -e

measure() {
python -m timeit \
    -s 'import logging, tracing' \
    -s 'logging.basicConfig(filename="/dev/null")' \
    -s "$1" \
    -s '
class Foo(object):
    def foo(self):
        tracing.trace("%s", "bar")
f = Foo()
' \
    'f.foo()'
}

echo tracing: Without patterns
measure "pass"

echo tracing: With unmatching pattern
measure 'tracing.trace_add_pattern("yikes")'

echo tracing: With matching pattern
measure 'tracing.trace_add_pattern("timeit-src")'


measure_logging() {
python -m timeit \
    -s 'import logging' \
    -s 'logging.basicConfig(filename="/dev/null")' \
    -s "$1" \
    -s '
class Foo(object):
    def foo(self):
        logging.debug("%s", "bar")
f = Foo()
' \
    'f.foo()'
}

echo logging: With debug messages
measure_logging pass

echo logging: Without debug messages
measure_logging \
    'logging.basicConfig(filename="/dev/null", level=logging.INFO)'
